-- MySQL Script generated by MySQL Workbench
-- Thu May 28 18:44:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`lista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lista` (
  `id_lista` INT NOT NULL AUTO_INCREMENT,
  `nombre_lista` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_lista`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtable1_UNIQUE` ON `mydb`.`lista` (`id_lista` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `mydb`.`usuario` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prioridad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prioridad` (
  `id_prioridad` INT NOT NULL,
  `nombre` CHAR(20) NOT NULL,
  PRIMARY KEY (`id_prioridad`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_prioridad_UNIQUE` ON `mydb`.`prioridad` (`id_prioridad` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`tarea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tarea` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tarea` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_lista` INT NOT NULL,
  `id_prioridad` INT NOT NULL,
  `nombre_tarea` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `fecha_limite` DATE NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tarea`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_lista`
    FOREIGN KEY (`id_lista`)
    REFERENCES `mydb`.`lista` (`id_lista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_prioridad`
    FOREIGN KEY (`id_prioridad`)
    REFERENCES `mydb`.`prioridad` (`id_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_tarea_UNIQUE` ON `mydb`.`tarea` (`id_tarea` ASC);

CREATE INDEX `id_usuario_idx` ON `mydb`.`tarea` (`id_usuario` ASC);

CREATE INDEX `id_lista_idx` ON `mydb`.`tarea` (`id_lista` ASC);

CREATE INDEX `id_prioridad_idx` ON `mydb`.`tarea` (`id_prioridad` ASC);

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view2` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view3` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
DROP VIEW IF EXISTS `mydb`.`view1` ;
USE `mydb`;


-- -----------------------------------------------------
-- View `mydb`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view2`;
DROP VIEW IF EXISTS `mydb`.`view2` ;
USE `mydb`;


-- -----------------------------------------------------
-- View `mydb`.`view3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view3`;
DROP VIEW IF EXISTS `mydb`.`view3` ;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`prioridad`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`prioridad` (`id_prioridad`, `nombre`) VALUES (1, 'Default');
INSERT INTO `mydb`.`prioridad` (`id_prioridad`, `nombre`) VALUES (2, 'Low');
INSERT INTO `mydb`.`prioridad` (`id_prioridad`, `nombre`) VALUES (3, 'Medium');
INSERT INTO `mydb`.`prioridad` (`id_prioridad`, `nombre`) VALUES (4, 'High');

COMMIT;

